title: "Fabio Oliveira's blog"
theme: jekyll-theme-slate
nav-bar links: 
  home: "fabio-a-oliveira.github.io"
social-network-links:
  email: "fabio.afdo@gmail.com"
  github: "https://github.com/fabio-a-oliveira"
  linkedin: "https://www.linkedin.com/in/fabioarbacholiveira/"
url-pretty: "fabio-a-oliveira.github.io"
